### ISSUE TITLE
ImportError: cannot import name 'get_eklt_corners' from 'utils.track_utils' 

### ISSUE THREAD

**Issue by saivenkateluru-github-io** [uzh-rpg/deep_ev_tracker#1]
Tried to run evaluate_real.py , faced the following issue
```
from utils.track_utils import (
ImportError: cannot import name 'get_eklt_corners' from 'utils.track_utils' (/home/user/deep_ev_tracker/utils/track_utils.py)
```

**Comment by MessikommerNico** [comment]
Thanks for pointing out this mistake. Since the 'get_eklt_corners' function is not used, the import statement can safely be removed. 
The code on the main branch is now updated accordingly.
