### ISSUE TITLE
For the SBT representation form, the sum of events of different polarity will be counteracted?

### ISSUE THREAD

**Issue by yanxiang-wang** [uzh-rpg/deep_ev_tracker#2]
Line 137 in the file representations.py:
```python
p0 = 2*events['p'].int()-1
p_bin = p0[idx0:idx1]
event_stack[i_bin, y_bin[i], x_bin[i]] += p_bin[i]
```

**Comment by MessikommerNico** [comment]
Apologies for the late response.

Yes, that is correct that the polarity is canceled out in the referenced lines. This is done for the EventStack representation. Unfortunately, we do have some inconsistencies in the naming. Our SBT representation is actually constructed similarly to the TimeSurface class in the same file (representations.py), which features separate bins for positive and negative events. See also e.g. [generate_event_representations.py](https://github.com/uzh-rpg/deep_ev_tracker/blob/master/data_preparation/synthetic/generate_event_representations.py) and [prepare_ec_pose_supervision.py](https://github.com/uzh-rpg/deep_ev_tracker/blob/master/data_preparation/real/prepare_ec_pose_supervision.py)
