### ISSUE TITLE
How can I test your tracker for my custom video?

### ISSUE THREAD

**Issue by FatihDemirtas** [uzh-rpg/deep_ev_tracker#4]
_Thank you for sharing your code with the community_

**Comment by MessikommerNico** [comment]
Thanks for your interest in our work!

To test our tracker on a custom video, I recommend starting with having a look and adapting the following files for your needs:

1. To generate the data, you can adapt the [prepare_eds_subseq.py](https://github.com/uzh-rpg/deep_ev_tracker/blob/master/data_preparation/real/prepare_eds_subseq.py) to obtain the timesurfaces required for the tracker. You can also experiment with the duration of the time window (dt) to achieve better performance. To use our data loaders, ensure that you have a similar data structure as the proposed training data.

2. To run the tracker, I recommend adapting the [evaluate_real.py](https://github.com/uzh-rpg/deep_ev_tracker/blob/master/evaluate_real.py) file. If you use the tracker in our framework (same data-loading, config files, etc.), this should be straight forward.

**Comment by calmelo** [comment]
> 1. you can adapt the

Can the project be used for real-time video?
