### ISSUE TITLE
Question about "To share information between features in the same image" in the paper 

### ISSUE THREAD

**Issue by yuyangpoi** [uzh-rpg/deep_ev_tracker#6]
May I ask where the 

"Since points on a rigid body exhibit correlated motion in the image plane, there is a substantial benefit in sharing information between features across the image. To achieve this, our frame attention module takes the feature vectors of all patches at the current timestep tj as input and computes the final displacement for each patch based on a self-attention weighted fusion of all feature vectors." 

 in the paper is reflected in the code? It seems that the multi-head attention in the code only processes one patch.

**Comment by MessikommerNico** [comment]
Yes, the information sharing is implemented in the code with a multi-head attention layer, see the following [line](https://github.com/uzh-rpg/deep_ev_tracker/blob/master/models/correlation3_unscaled.py#L244). All of the features in a frame are processed in parallel as different batch samples. Thus, a simple reshaping is enough to compute the attention over the features in one frame.
