### ISSUE TITLE
Multiflow dataset?

### ISSUE THREAD

**Issue by pppyj-m** [uzh-rpg/deep_ev_tracker#7]
Where can I find multiflow dataset? I cant find it anywhere.
HELP please~~

**Comment by yuyangpoi** [comment]
I can't find it either

**Comment by ctyfang** [comment]
Hey guys, sorry for the confusion. It hasn't been publicly released yet by the authors. For now, you can get a better understanding of the dataset from the paper https://arxiv.org/abs/2203.13674

**Comment by magehrig** [comment]
We have added the download links to the dataset [here](https://github.com/uzh-rpg/deep_ev_tracker#download-multiflow-dataset)
