### ISSUE TITLE
Training and dataset

### ISSUE THREAD

**Issue by ratom** [uzh-rpg/deep_ev_tracker#8]
Can you share the training code and dataset mentioned in the papers and github codes? I am interested to learn more, but, without running training and testing on my own computer, it seems a bit more challenging to get the concept described in the paper. It would be great if you provide the training and testing code to put more interest in your research and possibly can do more in this field as a research perspective. Thanks.

**Comment by magehrig** [comment]
The training code is available and we added the [download links](https://github.com/uzh-rpg/deep_ev_tracker#download-multiflow-dataset) for the multiflow dataset.

Does this answer your question?
