### ISSUE TITLE
Missing file "rectify_ec.py"

### ISSUE THREAD

**Issue by Ljiong201108** [uzh-rpg/deep_ev_tracker#9]
Hi! I noticed that the file `data_preparation/real/rectify_ec.py` mentioned in README section "Preparing Pose Data" is missing.  I would like to ask when you will upload it.

**Comment by samiarja** [comment]
Hi! I am also searching for this file. Where can I find it?

**Comment by MessikommerNico** [comment]
Apologies, this issue got lost.

I have added the script `rectify_ec.py` to the `data_preparation/real` directory, see commit 608655b997c6d58ae25a29d833551509888b4349
